giantswarm/cluster-standup-teardown

CHANGELOG.md
pkg/clusterbuilder/providers/capv/values/cluster_values.yaml

towards https://github.com/giantswarm/roadmap/issues/3372
Updates capv values to match refactored chart.

update cluster-vsphere values to match refactored chart

---

CHANGELOG.md
go.mod
go.sum

Bump clustertest to v1.1.0

---

CHANGELOG.md
go.mod
go.sum

Update clustertest to v1.3.1

---

CHANGELOG.md
go.mod
go.sum
pkg/teardown/teardown.go

Closes https://github.com/giantswarm/giantswarm/issues/31134

Use the E2E_WC_KEEP env var from clustertest

---

CHANGELOG.md
go.mod
go.sum
pkg/standup/standup.go

Correctly check if upgrade is valid

---

CHANGELOG.md
go.mod
go.sum

Bump releases SDK

---

CHANGELOG.md
pkg/clusterbuilder/client.go
pkg/clusterbuilder/providers/capz/private_cluster.go
pkg/clusterbuilder/providers/capz/values/private-cluster_values.yaml
pkg/clusterbuilder/providers/capz/values/private-default-apps_values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/30767
- Adds support for private CAPZ cluster

Add support for private CAPZ cluster

---

CHANGELOG.md
go.mod
go.sum
pkg/values/base.go

Populate more details in labels provided from the CICD pipelines on the Cluster and Org resources

Support more base labels

---

CHANGELOG.md
go.mod
go.sum

Update clustertest to v1.21.1

---

CHANGELOG.md
go.mod
go.sum

Correctly get latest GitHub release for Apps

---

CHANGELOG.md
pkg/clusterbuilder/providers/capvcd/values/cluster_values.yaml

Towards towards https://github.com/giantswarm/giantswarm/issues/31697
The name property is needed to make this migration work https://github.com/giantswarm/cluster-cloud-director/pull/365

add name property to cluster vcd

---

pkg/clusterbuilder/providers/capvcd/values/cluster_values.yaml

add proxy vars to capvcd values

---

CHANGELOG.md

add missed changelog entry

---

CHANGELOG.md
go.mod
go.sum

Updated clustertest with latest releases sdk

---

CHANGELOG.md
pkg/clusterbuilder/providers/capv/values/cluster_values.yaml

towards https://github.com/giantswarm/giantswarm/issues/31983

Drop deprecated values from cluster-vsphere tests

---

CHANGELOG.md
go.mod
go.sum

Updating clustertest 1.30.1

---

CHANGELOG.md
go.mod
go.sum

Bump clustertest

---

CHANGELOG.md
pkg/clusterbuilder/providers/capv/values/cluster_values.yaml

towards https://github.com/giantswarm/giantswarm/issues/31891

Update CAPV values to deploy on new Neoedge provider

---

CHANGELOG.md
pkg/standup/standup.go

Towards https://github.com/giantswarm/giantswarm/issues/32190

Increase timeout for cluster creation to 25 minutes

---

.nancy-ignore
CHANGELOG.md
cmd/standup/main.go
cmd/teardown/main.go
pkg/clusterbuilder/client.go
pkg/standup/standup.go
pkg/values/values.go

Towards: https://github.com/giantswarm/giantswarm/issues/33010

Fix linting issues

---

CHANGELOG.md
pkg/clusterbuilder/providers/capa/private_cluster.go

Towards https://github.com/giantswarm/giantswarm/issues/30795

Adjust CAPA private cluster tests to suit `garm` setup (#237)

---

CHANGELOG.md
pkg/clusterbuilder/providers/capa/values/private-cluster_values.yaml

Fix private cluster baseDomain

---

CHANGELOG.md
pkg/clusterbuilder/providers/capvcd/values/cluster_values.yaml

Increase CAPVCD nodes disk size

---

CHANGELOG.md
cmd/standup/main.go

Towards https://github.com/giantswarm/giantswarm/issues/33938

Don't rely on workers having labels
